PROBLEM STATEMENT :
Create an “Academic performance” dataset of students and perform the following operations using Python :
1. Scan all variables for missing values and inconsistencies. If there are missing values and/or inconsistencies, use any of the suitable techniques to deal with them. 
2. Scan all numeric variables for outliers. If there are outliers, use any of the suitable techniques to deal with them. 
3. Apply data transformations on at least one of the variables. The purpose of this transformation should be one of the following reasons: to change the scale for better understanding of the variable, to convert a non-linear relation into a linear one, or to decrease the skewness and convert the distribution into a normal distribution.

1. IMPORT ALL THE REQUIRED LIBRARIES

In [2]:
import pandas as pd
import numpy as np

2. LOAD THE DATASET USING PANDAS

In [3]:
df = pd.read_csv('student_score2.csv')
df.head()

,math score,reading score,writing score,placement score,club join year,placement offer count
0,74,82.0,62,100,2019,3
1,79,80.0,67,83,2018,2
2,74,86.0,69,85,2021,3
3,76,90.0,71,111,2019,3
4,61,83.0,73,79,2018,2

3. CHECK FOR INCONSISTENCIES

In [4]:
df.isnull().sum()

math score               0
reading score            1
writing score            0
placement score          0
club join year           0
placement offer count    0
dtype: int64

4. HANDLING INCONSISTENCIES

In [5]:
df.fillna({"reading score": df["reading score"].mean()}, inplace=True)
print(df.isnull().sum())

math score               0
reading score            0
writing score            0
placement score          0
club join year           0
placement offer count    0
dtype: int64

5. DETECTING OUTLIERS USING IQR

In [6]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

# Find outliers
outliers = ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR)))
outliers.sum()

math score               0
reading score            0
writing score            0
placement score          0
club join year           0
placement offer count    0
dtype: int64

6. REMOVE OUTLIERS

In [7]:
df_no_outliers = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

df_no_outliers.shape

(30, 6)

7. DATA TRANSFORMATION : LOG TRANSFORMATION

In [8]:
# Apply log transformation on numeric columns
for col in df_no_outliers.select_dtypes(include=np.number):
    df_no_outliers[col] = np.log1p(df_no_outliers[col])

df_no_outliers.head()

,math score,reading score,writing score,placement score,club join year,placement offer count
0,4.317488,4.418841,4.143135,4.615121,7.610853,1.386294
1,4.382027,4.394449,4.219508,4.430817,7.610358,1.098612
2,4.317488,4.465908,4.248495,4.454347,7.611842,1.386294
3,4.343805,4.510860,4.276666,4.718499,7.610853,1.386294
4,4.127134,4.430817,4.304065,4.382027,7.610358,1.098612